name: Build and Tag Wazuh Agent Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-wazuh

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os:
        - name: centos
          version:
            - latest
            - 8
            - 7
        - name: opensuse
          version:
            - latest
            - 15
        - name: ubuntu
          version:
            - latest
            - jammy
            - focal
            - noble
        - name: debian
          version:
            - latest
            - buster
        - name: alpine
          version:
            - latest
            - edge
            - 3
        - name: fedora
          version:
            - latest
            - 41
            - 40

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to the Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: lowercase
        uses: AsZc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ steps.lowercase.outputs.lowercase }}
          tags: |
            type=raw,value=${{ matrix.os.name }}-${{ matrix.os.version }}

      - name: Build and push
        uses: docker/build-push-action@v4
        continue-on-error: true
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          target: ${{ matrix.os.name }}
          build-args: |
            CENTOS_VERSION=${{ matrix.os.version }}
            OPENSUSE_VERSION=${{ matrix.os.version }}
            UBUNTU_VERSION=${{ matrix.os.version }}
            DEBIAN_VERSION=${{ matrix.os.version }}
            ALPINE_VERSION=${{ matrix.os.version }}
            FEDORA_VERSION=${{ matrix.os.version }}
