name: Build and Tag Bats Docker Images

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        include:
        - os: centos
          version: latest
        - os: centos
          version: 8
        - os: centos
          version: 7

        - os: opensuse
          version: latest
        - os: opensuse
          version: 15

        - os: ubuntu
          version: latest
        - os: ubuntu
          version: jammy
        - os: ubuntu
          version: focal
        - os: ubuntu
          version: noble

        - os: debian
          version: latest
        - os: debian
          version: buster

        - os: alpine
          version: latest
        - os: alpine
          version: edge
        - os: alpine
          version: 3

        - os: fedora
          version: latest
        - os: fedora
          version: 41
        - os: fedora
          version: 40

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to the Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: lowercase
        name: Lowercase repository name
        uses: AsZc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ steps.lowercase.outputs.lowercase }}
          tags: |
            type=raw,value=${{ matrix.os }}-${{ matrix.version }}

      - name: Cache Docker layers
        uses: actions/cache@v4
        if: github.ref == 'refs/heads/main'
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.os }}-${{ matrix.version }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.os }}-${{ matrix.version }}-

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.ref == 'refs/heads/main' && 'true' || 'false' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          target: ${{ matrix.os }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          build-args: |
            CENTOS_VERSION=${{ matrix.version }}
            OPENSUSE_VERSION=${{ matrix.version }}
            UBUNTU_VERSION=${{ matrix.version }}
            DEBIAN_VERSION=${{ matrix.version }}
            ALPINE_VERSION=${{ matrix.version }}
            FEDORA_VERSION=${{ matrix.version }}

      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        if: github.ref == 'refs/heads/main'
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache